### ISSUE TITLE
Complete Selfhosted Project via Docker

### ISSUE THREAD

**Issue by Ruff-G** [vishnuraghavb/EnBizCard#11]
Hello Vishnu Raghav B,

this is a very nice and best ever seen business card. Congratulations.
It would be nice to host this project via docker. Is this in your plans or could you setup a walkthrough to host it on docker?

A good plan would be to generate cards and than you get a direct link to the generated card (no .zip download).

**Comment by vishnuraghavb** [comment]
Hi, Thanks and I'm glad that you like the project. Yes I do have plans for making it completely self-hostable but I am not gonna work on that anytime soon. Right now, hosting EnBizCard is not recommended since it doesn't help what you are aiming for. So for now you have to stay tune...
