### ISSUE TITLE
Physical address / vCard ADR property

### ISSUE THREAD

**Issue by cpy82** [vishnuraghavb/EnBizCard#12]
Hello Vishnu Raghav,

wonderful project! Thank you very much!

Would it be possible to add a field for the physical address so that the address is correctly stored in the vCard property "ADR"? If possible also with distinction between Home and Work.

Thank you!

**Comment by Satvik-web** [comment]
Hi @cpy82!
Greetings form India, TamilNadu..

if you are using C#.. There is an awesome nuget package called VCard which helps you to create VCards easily..
You can just find more info in the implementation blog (Make sure you read it fully)..

Link : https://www.nuget.org/packages/VCard/

Github : https://github.com/Satvik-web/VCard

Implementation blog : https://satvikr.blogspot.com

Or you can search for Card in VS manage nuget packages tab and install the package in the 3rd result..

**Comment by vishnuraghavb** [comment]
Hi @cpy82,

Your suggestion has been added.

Thanks. Keep supporting!
