### ISSUE TITLE
Bump tailwind version

### ISSUE THREAD

**Issue by shaynem** [vishnuraghavb/EnBizCard#17]
Since PR's or Issues are stale.

if anyone is having issues installing on node 17 - see below.

```error postcss-nesting@8.0.1: The engine "node" is incompatible with this module. Expected version "12 - 16". Got "17.6.0"```

 @nuxtjs/tailwindcss ^4.2.1 - not compatible with node version 17 

 bump version to 5.0.4 

```package.json```
```json
"@nuxtjs/tailwindcss": "^5.0.4"
```

In order to run ```yarn build``` to generate nuxt build on node 17, will require env 

Mac & Linux
```bash
export NODE_OPTIONS=--openssl-legacy-provider
```
Windows
```ps
set NODE_OPTIONS=--openssl-legacy-provider
```

**Comment by vishnuraghavb** [comment]
Fixed!
