### ISSUE TITLE
vishnuraghavb/enbizcard is the right repository?

### ISSUE THREAD

**Issue by mariushosting** [vishnuraghavb/EnBizCard#23]
docker: Error response from daemon: pull access denied for vishnuraghavb/enbizcard, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Comment by vishnuraghavb** [comment]
EnBizCard is not officially available on Docker. You may have to manually clone the GitHub repo locally and build it using docker-compose just like in the readme instructions.
