### ISSUE TITLE
Host it at scale

### ISSUE THREAD

**Issue by JoshBuch** [vishnuraghavb/EnBizCard#25]
Is there any way we can host this application at scale for a large number of users. For example, instead of asking end users to create their business cards individually, what if we the application owner can create business cards for the users by reading them from an excel file or integrating the application with azure active directory for example.

**Comment by vishnuraghavb** [comment]
The project's main purpose is to generate the files required to host the digital business cards on one's server. So, right now, I can't do that because it would be outside the scope of this project.
