### ISSUE TITLE
Save state locally

### ISSUE THREAD

**Issue by AlexDaichendt** [vishnuraghavb/EnBizCard#27]
Would it be possible to add a button which saves the current state of the application in LocalStorage?

**Comment by shiggins8** [comment]
Additional comment - even if there was a way to export the state as a JSON or XML that could be imported for editing/tweaking later on, that would be a useful feature.

**Comment by pranavmishra90** [comment]
Saving / exporting the current state could also allow for tracking the repo via git, which would be great for making updates as they come along

**Comment by codeman256** [comment]
Love it if we could save the config to then import and edit later too!

**Comment by vishnuraghavb** [comment]
It is good to know that many people are interested in this feature. But EnBizcard is still under development and doesn't follow a standard structure. As features can be added or removed at any time, I cannot guarantee that exported data will be imported without problems in future updates, so I have skipped the export/import idea for now. Once the application is mature enough, this feature will definitely be added.
