### ISSUE TITLE
Website alignment is off when loaded to host

### ISSUE THREAD

**Issue by tee2nu22** [vishnuraghavb/EnBizCard#31]
Website alignment is off when loaded to host.  After downloading the zip file and uploading the files to my web hosting site and launching, everything is not where it is supposed to be.  Words are jumbled together and images not aligned.  Is there something I need to do? here's the site:  http://bh1.thielruperto.com/trvcard1/

Here is what it looks like during the creation of the card: 
1)  https://bh1.thielruperto.com/sharedimages/bcardimage1.png
2) https://bh1.thielruperto.com/sharedimages/bcardimage2.png

Please help!

**Comment by vishnuraghavb** [comment]
I think you might have fixed your issue already. To me, everything looks fine at your provided URL. 🙂 
If not, please let me know. The issue should be that your stylesheets are not located in the right folder.

**Comment by tee2nu22** [comment]
Try it again. I just uploaded the files from your site.  This is the format I want. But is not coming out correctly.  Please help on how to fix it.  Thank you.

Thiel
________________________________

**Comment by tee2nu22** [comment]
![image](https://user-images.githubusercontent.com/41484329/207647330-6962291f-5ea3-465b-b6e1-148014e29dc1.png)

**Comment by vishnuraghavb** [comment]
Your digital card looks good to me on all of my browsers. I'm not sure exactly what you think is wrong; could you share a screenshot of what you see on your browser instead?
Also, give CTRL+SHIFT+R a serious try while refreshing your browser tab.
Hope this was useful.

**Comment by vishnuraghavb** [comment]
The file folder structure looks perfect to me. No issue with that. I suspect it is something with your browser cache. Did you try viewing your card on different browsers or computer/mobile?

**Comment by tee2nu22** [comment]
Thank you!!  It was the cache.  Once I cleared it, it works now.  Thanks again! 🙂
________________________________
