### ISSUE TITLE
iphone display issue

### ISSUE THREAD

**Issue by alkisal** [vishnuraghavb/EnBizCard#33]
Hello, congrats on your excellent work

however I am facing an issue.
while everything works fine on android, on iphone display LOGO overlaps with profile photo during portrait (normal position of display) while it works fine during landscape (screen rotation sideways).

this doesn't happen on android where all works like a dream.
any thoughts please

thanks a lot
alkis

**Comment by Brantlab** [comment]
@vishnuraghavb I believe I have a fix for this by removing `Height:100%` from the css files. As noted below I removed this and tested and did not find any issues. I attempted to do a pull request but I lack permissions and such and really a novice at Github. 

`.headerImgC{display:grid;grid-template-columns:auto;grid-template-rows:auto;overflow:hidden}`

**Comment by Brantlab** [comment]
@alkisal I submitted a PR to fix this I hope

**Comment by StarWhiz** [comment]
I can confirm this happens on newer iphones as well.

**Comment by vishnuraghavb** [comment]
@Brantlab Merged your PR. Thanks. Sorry for the delayed response!
