### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by mbh-dev** [vishnuraghavb/EnBizCard#4]
Hi,

Do you have any installation instructions so that we can host this application ourselves?

Thanks

**Comment by bullride** [comment]
Hi there @vishnuraghavb 

Yes, agree with @mbh-dev - Could you please assist with Installation Instructions please.

Thanking you in advance

**Comment by vishnuraghavb** [comment]
Hello,
I see no purpose in installing this webapp on your server, since it is not a installable server in itself. If you have a solid purpose, please let us know. Thanks.
