### ISSUE TITLE
OpenPGP field does not allow SMIME key

### ISSUE THREAD

**Issue by RideMyByte** [vishnuraghavb/EnBizCard#49]
Hello everyone! 
Great software, thank you very much! 
The OpenPGP field does not allow SMIME keys because of “Invalid schema”. Would be great if this were allowed, as SMIME is used more often than OpenPGP, especially in a professional context, unfortunately. 

Greetings from Germany

**Comment by vishnuraghavb** [comment]
Hi. Thanks for using EnBizCard!
It will be fixed in the upcoming release soon.
