### ISSUE TITLE
Business name not populating

### ISSUE THREAD

**Issue by NTinfinitumnihil** [vishnuraghavb/EnBizCard#9]
Hello - this is a wonderful project you have created - 

in testing, i find upon deployment to my server that all works except it seems the business name is not getting rendered.

to whit, the html does not reflect any code to suggest business name is there, while name, phone numbers, email, etc work fine

any thoughts?

**Comment by vishnuraghavb** [comment]
That's how it's supposed to work. Because the company's name would be printed on the logo. I didn't think it was necessary to bring it up again. Only the vcard *.vcf file contains the business name.

**Comment by vishnuraghavb** [comment]
Consider a business card that has been printed. We'd include our company logo, as well as our name, job position, and contact information. We rarely see business names spelled out twice.
